const categoryData = [
  {
    id: 1,
    name: 'hats',
    text: 'Shop Now',
    // image: './vite.svg',
    image: 'https://i.ibb.co/cvpntL1/hats.png',
    // linkURL: 'shop/hats',
    linkURL: '/',
    rowNum: 1,
    nCols: 2,
    colStart: 1,
    colEnd: 3,
  },
  {
    id: 2,
    name: 'jackets',
    text: 'Shop Now',
    // image: './vite.svg',
    image: 'https://i.ibb.co/px2tCc3/jackets.png',
    // linkURL: 'shop/jackets',
    linkURL: '/',
    rowNum: 1,
    nCols: 2,
    colStart: 3,
    colEnd: 5,
  },
  {
    id: 3,
    name: 'sneakers',
    text: 'Shop Now',
    // image: './vite.svg',
    image: 'https://i.ibb.co/0jqHpnp/sneakers.png',
    // linkURL: 'shop/sneakers',
    linkURL: '/',
    rowNum: 1,
    nCols: 2,
    colStart: 5,
    colEnd: 7,
  },
  {
    id: 4,
    name: 'womens',
    text: 'Shop Now',
    // image: './vite.svg',
    image: 'https://i.ibb.co/GCCdy8t/womens.png',
    // linkURL: 'shop/womens',
    linkURL: '/',
    rowNum: 2,
    colStart: 1,
    colEnd: 4,
  },
  {
    id: 5,
    name: 'mens',
    text: 'Shop Now',
    // image: './vite.svg',
    image: 'https://i.ibb.co/R70vBrQ/men.png',
    // linkURL: 'shop/mens',
    linkURL: '/',
    rowNum: 2,
    nCols: 3,
    colStart: 4,
    colEnd: 7,
  },
];

export default categoryData;
